set (SPD_INSTALL_SCRIPT ${CMAKE_SOURCE_DIR}/.cmake/spdlog_install.cmake)

ExternalProject_Add(
    spdlog
    GIT_REPOSITORY https://github.com/gabime/spdlog.git
    PREFIX "${EXTERNAL_PREFIX}"
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=Release
    INSTALL_COMMAND cmake -DSPD_BUILD_DIR=${EXTERNAL_PREFIX}/src/spdlog -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=Release -P ${SPD_INSTALL_SCRIPT}
)
